= GR8 CRM - Public Profile Plugin
Göran Ehrsson <goran@technipelago.se>
:description: Official documentation for the GR8 CRM Public Profile Plugin
:keywords: groovy, grails, crm, gr8crm, documentation
:toc:
:numbered:
:icons: font
:imagesdir: ./images
:source-highlighter: prettify
:homepage: http://gr8crm.github.io
:gr8crm: GR8 CRM
:gr8source: https://github.com/technipelago/grails-crm-public-profile
:license: This plugin is licensed with http://www.apache.org/licenses/LICENSE-2.0.html[Apache License version 2.0]

== Introduction

{gr8crm} is a set of http://www.grails.org/[Grails Web Application Framework]
plugins that makes it easy to develop web applications with CRM functionality.

You can find more information about {gr8crm} on the main documentation site {homepage}.

=== Customer Relationship Management

Customer relationship management (CRM) is a system for managing a company’s interactions with current and future customers.
It involves using technology to organize, automate and synchronize sales, marketing, customer service, and technical support.
http://en.wikipedia.org/wiki/Customer_relationship_management[Wikipedia]

The {gr8crm} "Ecosystem" currently contains over 40 Grails plugins. For a complete list of plugins see {homepage}.

Each {gr8crm} plugin defines a http://martinfowler.com/bliki/BoundedContext.html[Bounded Context]
that focus on one specific domain, for example *contact*, *project* or *document*.

== Public Profile Plugin

This plugin can publish contact information on a public web site.
Users can manage their contact information, upload photos, etc.
This information can then be rendered with generic templates in a web page.

The motivation for this plugin was to provide a way for dealers to manage their contact information
on a central site. Dealers could upload photos, provide accurate information like opening hours, etc.
Dealer information was then presented on a central site for visitors to search for nearby dealers.

Contact information is stored using the http://gr8crm.github.io/plugins/crm-contact/[crm-contact] plugin.
This plugin gives you all standard contact information properties like name, telephone, address, etc.

Media (photos) are stored using the http://gr8crm.github.io/plugins/crm-content/[crm-content] plugin.

By leveraging other {gr8crm} plugins this plugin is quite small. It just package functionality from
other plugins in a user friendly way.

== Changes

2.4.0:: First public release

== License

{license}

== Source Code

The source code for this plugin is available at {gr8source}
